#pragma once

// /* 定义 Caterina-leonardo PID
// 因为leonardo的PID是0x8036
// 但是keyboard.json文件没有配置过leonardo的PID */
// #undef CATERINA_PID
// #define CATERINA_PID 0x8036
// 无效

/* 按键矩阵尺寸 */
#define MATRIX_ROWS 4
#define MATRIX_COLS 12

/* 去抖动设置 */
#define DEBOUNCE 5

// /* 命令的按键组合 */
// #define IS_COMMAND() (keyboard_report->mods == (MOD_BIT(KC_LSHIFT) | MOD_BIT(KC_RSHIFT)))

/* RGB矩阵设置 */
#define WS2812_DI_PIN F1
// #define DRIVER_LED_TOTAL 43
// #define RGB_MATRIX_LED_COUNT 43
#define RGB_MATRIX_CENTER {110, 31}
// TT连按次数
#define TAPPING_TOGGLE 2

// GRB刷新频率
#define RGB_MATRIX_LED_FLUSH_LIMIT 16

// 限制LED处理数量
// #define RGB_MATRIX_LED_PROCESS_LIMIT 4

// 睡眠模式
// #define RGB_MATRIX_SLEEP

/* RGB Matrix效果配置 - 精简版 */
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE // 静态颜色
// #define ENABLE_RGB_MATRIX_BREATHING      // 呼吸
// #define ENABLE_RGB_MATRIX_MULTISPLASH    // 多重彩虹扩散
// #define ENABLE_RGB_MATRIX_TYPING_HEATMAP   // 打字热力图
// #define ENABLE_RGB_MATRIX_STARLIGHT_SMOOTH // 星光平滑

// #define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT  // 双色星光饱和度
// #define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS //  糖果雨滴
// #define ENABLE_RGB_MATRIX_FLOWER_BLOOMING     //  花朵绽放
// #define ENABLE_RGB_MATRIX_STARLIGHT_SMOOTH    // 星光平滑
// #define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE  // 双色星光
// #define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT  // 双色星光
/*-------------------------------------------------------------------*/
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE	   
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS	
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS	
#define ENABLE_RGB_MATRIX_SPLASH	
#define ENABLE_RGB_MATRIX_MULTISPLASH	
#define ENABLE_RGB_MATRIX_SOLID_SPLASH	
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH	
#define ENABLE_RGB_MATRIX_ALPHAS_MODS	
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN	
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT	
#define ENABLE_RGB_MATRIX_BREATHING	
#define ENABLE_RGB_MATRIX_BAND_SAT	
#define ENABLE_RGB_MATRIX_BAND_VAL	
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT	
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL	
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT	
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL	
#define ENABLE_RGB_MATRIX_CYCLE_ALL	
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT	
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN	
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON	
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN	
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL	
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL	
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL	
#define ENABLE_RGB_MATRIX_DUAL_BEACON	
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON	
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS	
#define ENABLE_RGB_MATRIX_FLOWER_BLOOMING	
#define ENABLE_RGB_MATRIX_RAINDROPS	
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS	
#define ENABLE_RGB_MATRIX_HUE_BREATHING	
#define ENABLE_RGB_MATRIX_HUE_PENDULUM	
#define ENABLE_RGB_MATRIX_HUE_WAVE	
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL	
#define ENABLE_RGB_MATRIX_PIXEL_FLOW	
#define ENABLE_RGB_MATRIX_PIXEL_RAIN	
#define ENABLE_RGB_MATRIX_STARLIGHT	
#define ENABLE_RGB_MATRIX_STARLIGHT_SMOOTH	
#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE	
#define ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT	
#define ENABLE_RGB_MATRIX_RIVERFLOW	
/*-------------------------------------------------------------------*/
// RGB Matrix默认设置
#define RGB_MATRIX_DEFAULT_HUE 38  // 色调
#define RGB_MATRIX_DEFAULT_SAT 255 // 饱和度
#define RGB_MATRIX_DEFAULT_SPD 127 // 速度
#define RGB_MATRIX_DEFAULT_VAL 200 // 亮度

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 220 // 亮度最大值


#define DYNAMIC_KEYMAP_LAYER_COUNT 8  // 最大按键层数